name: Release

on:
  push:
    tags: ["v*"]

permissions: {}

jobs:
  create_release:
    name: Create release
    permissions:
      contents: write # For creating a release
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: woof ${{ github.ref_name }}
  build:
    name: Build binaries
    permissions:
      contents: write # For uploading release artifacts
    needs: create_release
    strategy:
      matrix:
        settings:
          - host: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - host: macos-latest
            target: x86_64-apple-darwin
          - host: macos-latest
            target: aarch64-apple-darwin
          - host: windows-latest
            target: x86_64-pc-windows-msvc
            bin_suffix: .exe
    runs-on: ${{ matrix.settings.host }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: "${{ needs.stage.outputs.stage-branch }}"
      # Set the version to the release tag
      - name: Set CLI version
        shell: bash
        env:
          RELEASE_TAG: ${{ github.ref_name }}
        run: |
          echo "Setting version to $RELEASE_TAG"
          sed -i'' -e "s/^version = \"0\.0\.0-dev\"/version = \"${RELEASE_TAG#v}\"/" Cargo.toml
      - name: Setup rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ matrix.settings.target }}
          rustflags: "" # Prevent default override
          cache: false # TODO: Configure caching
      - name: Build
        run: ${{ matrix.settings.rust-build-env }} cargo build --release --target ${{ matrix.settings.target }}
      - name: Prepare artifacts
        run: |
          mkdir dist
          mv ./target/${{ matrix.settings.target }}/release/woof${{ matrix.settings.bin_suffix }} ./dist/woof-${{ matrix.settings.target }}${{ matrix.settings.bin_suffix }}
      - name: Add artifacts to release
        uses: softprops/action-gh-release@v2
        with:
          files: ./dist/*
